#ifndef __APP_SETTING_H__
#define __APP_SETTING_H__


#define SETTING_KEY_MODE "MODE"
#define SETTING_KEY_PROBE_NAME "PROBE_NAME"
#define SETTING_KEY_PROBE_CARD_CAPACITY "PROBE_CARD_CAPACITY"
#define SETTING_KEY_BLE_IDENTIFIER "BLE_IDENTIFIER"
#define SETTING_KEY_BLE_SERVICE_UUID "BLE_SERVICE_UUID"
#define SETTING_KEY_BLE_CHARACTERISTICS_UUID "BLE_CHARACTERISTICS_UUID"


#endif /* __APP_SETTING_H__ */