(function (ns) {
	if(	ns.Defines )
	{
		return;
	}

    ns.Defines = {}
    ns.Defines.VERSION = "00.03.00";

    ns.Defines.PLAYER_PROBE_LIST = [
        "Seat01",
        "Seat02",
        "Seat03",
        "Seat04",
        "Seat05",
        "Seat06",
        "Seat07",
        "Seat08",
        "Seat09",
    ];
    ns.Defines.PLAYER_PROBE_PREFIX = "Seat";
    ns.Defines.DEALER_PROBE_PREFIX = "Dealer";

	// ブルートゥース関連
	ns.Defines.BLE_DEVICE_NAME_PREFIX = "PTV_PP_";
	ns.Defines.BLE_UUID_SERVICE = "cbaabb28-4e81-49c4-b775-aedfd27d8db0";
	ns.Defines.BLE_UUID_CHARACTERISTIC_TX = "45f116ee-b087-4271-888d-a15eebebd2eb"; // デバイス→ブラウザ
	ns.Defines.BLE_UUID_CHARACTERISTIC_RX = "45f116ee-b087-4271-888d-a15eebebd2ee"; // ブラウザ→デバイス

    // HTML コマンド実行関連
    ns.Defines.COMMAND_PROVE_DEVICE_MANAGER_SCAN = "COMMAND_PROVE_DEVICE_MANAGER_SCAN";
    ns.Defines.COMMAND_DEVELOP_PROVE_DEVICE_MANAGER_DUMP_STATUS = "COMMAND_DEVELOP_PROVE_DEVICE_MANAGER_DUMP_STATUS";
	ns.Defines.COMMAND_DEVELOP_PROVE_DEVICE_MANAGER_TEST_SCAN_OFF = "COMMAND_DEVELOP_PROVE_DEVICE_MANAGER_TEST_SCAN_OFF";
	ns.Defines.COMMAND_DEVELOP_PROVE_DEVICE_MANAGER_TEST_SCAN_ON = "COMMAND_DEVELOP_PROVE_DEVICE_MANAGER_TEST_SCAN_ON";
	ns.Defines.COMMAND_DEVELOP_PROVE_DEVICE_MANAGER_DEBUG_DEAL_CARD = "COMMAND_DEVELOP_PROVE_DEVICE_MANAGER_DEBUG_DEAL_CARD";
	ns.Defines.COMMAND_DEVELOP_PROVE_DEVICE_MANAGER_DEBUG_FLOP = "COMMAND_DEVELOP_PROVE_DEVICE_MANAGER_DEBUG_FLOP";
	ns.Defines.COMMAND_DEVELOP_PROVE_DEVICE_MANAGER_DEBUG_TURN = "COMMAND_DEVELOP_PROVE_DEVICE_MANAGER_DEBUG_TURN";
	ns.Defines.COMMAND_DEVELOP_PROVE_DEVICE_MANAGER_DEBUG_RIVER = "COMMAND_DEVELOP_PROVE_DEVICE_MANAGER_DEBUG_RIVER";

	// HTML コンテナ
	ns.Defines.CONTAINER_PROBEPLAYER_PANEL = "CONTAINER_PROBEPLAYER_PANEL";
	ns.Defines.CONTAINER_PROBEDEALER_PANEL = "CONTAINER_PROBEDEALER_PANEL";
	ns.Defines.CONTAINER_MONITORPLAYER_PANEL = "CONTAINER_MONITORPLAYER_PANEL";
	ns.Defines.CONTAINER_MONITORDEALER_PANEL = "CONTAINER_MONITORDEALER_PANEL";

	// HTML テンプレート: カードまわり
	ns.Defines.TEMPLATE_GLOBAL_CARD_NORMAL = "TEMPLATE_GLOBAL_CARD_NORMAL";
	ns.Defines.TEMPLATE_GLOBAL_CARD_SMALL = "TEMPLATE_GLOBAL_CARD_SMALL";

	// HTML テンプレート: プローブパネル(共通)
    ns.Defines.TEMPLATE_PROBE_PANEL_STATUS_LABEL = "TEMPLATE_PROBE_PANEL_STATUS_LABEL";
    ns.Defines.TEMPLATE_PROBE_PANEL_STATUS_VALUE = "TEMPLATE_PROBE_PANEL_STATUS_VALUE";
    ns.Defines.TEMPLATE_PROBE_PANEL_BATTERY_LABEL = "TEMPLATE_PROBE_PANEL_BATTERY_LABEL";
    ns.Defines.TEMPLATE_PROBE_PANEL_BATTERY_VALUE = "TEMPLATE_PROBE_PANEL_BATTERY_VALUE";
    ns.Defines.TEMPLATE_PROBE_PANEL_LASTUPDATE_LABEL = "TEMPLATE_PROBE_PANEL_LASTUPDATE_LABEL";
    ns.Defines.TEMPLATE_PROBE_PANEL_LASTUPDATE_VALUE = "TEMPLATE_PROBE_PANEL_LASTUPDATE_VALUE";
	ns.Defines.TEMPLATE_PROBE_PANEL_CONTROL_RESCAN = "TEMPLATE_PROBE_PANEL_CONTROL_RESCAN";

	// HTML テンプレート: プローブパネル(プレイヤー)
	ns.Defines.TEMPLATE_PROBEPLAYER_PANEL = "TEMPLATE_PROBEPLAYER_PANEL";
    ns.Defines.TEMPLATE_PROBEPLAYER_PANEL_STATUS = "TEMPLATE_PROBEPLAYER_PANEL_STATUS";
    ns.Defines.TEMPLATE_PROBEPLAYER_PANEL_BATTERY = "TEMPLATE_PROBEPLAYER_PANEL_BATTERY";
    ns.Defines.TEMPLATE_PROBEPLAYER_PANEL_NAME = "TEMPLATE_PROBEPLAYER_PANEL_NAME";
    ns.Defines.TEMPLATE_PROBEPLAYER_PANEL_NAME_LABEL = "TEMPLATE_PROBEPLAYER_PANEL_NAME_LABEL";
    ns.Defines.TEMPLATE_PROBEPLAYER_PANEL_NAME_VALUE = "TEMPLATE_PROBEPLAYER_PANEL_NAME_VALUE";
    ns.Defines.TEMPLATE_PROBEPLAYER_PANEL_NICK = "TEMPLATE_PROBEPLAYER_PANEL_NICK";
    ns.Defines.TEMPLATE_PROBEPLAYER_PANEL_NICK_LABEL = "TEMPLATE_PROBEPLAYER_PANEL_NICK_LABEL";
    ns.Defines.TEMPLATE_PROBEPLAYER_PANEL_NICK_INPUT = "TEMPLATE_PROBEPLAYER_PANEL_NICK_INPUT";
    ns.Defines.TEMPLATE_PROBEDEALER_PANEL_LASTUPDATE = "TEMPLATE_PROBEDEALER_PANEL_LASTUPDATE";
	ns.Defines.TEMPLATE_PROBEPLAYER_PANEL_ACTION = "TEMPLATE_PROBEPLAYER_PANEL_ACTION";
	ns.Defines.TEMPLATE_PROBEPLAYER_PANEL_ACTION_FOLD = "TEMPLATE_PROBEPLAYER_PANEL_ACTION_FOLD";
	ns.Defines.TEMPLATE_PROBEPLAYER_PANEL_ACTION_CHECK = "TEMPLATE_PROBEPLAYER_PANEL_ACTION_CHECK";
	ns.Defines.TEMPLATE_PROBEPLAYER_PANEL_ACTION_BET = "TEMPLATE_PROBEPLAYER_PANEL_ACTION_BET";
	ns.Defines.TEMPLATE_PROBEPLAYER_PANEL_ACTION_CALL = "TEMPLATE_PROBEPLAYER_PANEL_ACTION_CALL";  
	ns.Defines.TEMPLATE_PROBEPLAYER_PANEL_ACTION_RAISE = "TEMPLATE_PROBEPLAYER_PANEL_ACTION_RAISE"; 
	ns.Defines.TEMPLATE_PROBEPLAYER_PANEL_ACTION_ALLIN = "TEMPLATE_PROBEPLAYER_PANEL_ACTION_ALLIN";
	ns.Defines.TEMPLATE_PROBEPLAYER_PANEL_CONTROL = "TEMPLATE_PROBEPLAYER_PANEL_CONTROL";
	ns.Defines.TEMPLATE_PROBEPLAYER_PANEL_CONTROL_ALIVE = "TEMPLATE_PROBEPLAYER_PANEL_CONTROL_ALIVE";
	ns.Defines.TEMPLATE_PROBEPLAYER_PANEL_HOLECARD = "TEMPLATE_PROBEPLAYER_PANEL_HOLECARD";
	ns.Defines.TEMPLATE_PROBEPLAYER_PANEL_HOLECARD_VALUE = "TEMPLATE_PROBEPLAYER_PANEL_HOLECARD_VALUE";
	ns.Defines.TEMPLATE_PROBEPLAYER_PANEL_CONTROL_POSITION = "TEMPLATE_PROBEPLAYER_PANEL_CONTROL_POSITION";

	// HTML テンプレート: プローブパネル(ディーラー)
	ns.Defines.TEMPLATE_PROBEDEALER_PANEL = "TEMPLATE_PROBEDEALER_PANEL";
    ns.Defines.TEMPLATE_PROBEDEALER_PANEL_STATUS = "TEMPLATE_PROBEDEALER_PANEL_STATUS";
    ns.Defines.TEMPLATE_PROBEDEALER_PANEL_BATTERY = "TEMPLATE_PROBEDEALER_PANEL_BATTERY";
	ns.Defines.TEMPLATE_PROBEDEALER_PANEL_BOARD = "TEMPLATE_PROBEDEALER_PANEL_BOARD";
	ns.Defines.TEMPLATE_PROBEDEALER_PANEL_FLOP_VALUE = "TEMPLATE_PROBEDEALER_PANEL_FLOP_VALUE";
	ns.Defines.TEMPLATE_PROBEDEALER_PANEL_TURN_VALUE = "TEMPLATE_PROBEDEALER_PANEL_TURN_VALUE";
	ns.Defines.TEMPLATE_PROBEDEALER_PANEL_RIVER_VALUE = "TEMPLATE_PROBEDEALER_PANEL_RIVER_VALUE";
	ns.Defines.TEMPLATE_PROBEDEALER_PANEL_BLIND = "TEMPLATE_PROBEDEALER_PANEL_BLIND";
	ns.Defines.TEMPLATE_PROBEDEALER_PANEL_BLIND_SB_INPUT = "TEMPLATE_PROBEDEALER_PANEL_BLIND_SB_INPUT";
	ns.Defines.TEMPLATE_PROBEDEALER_PANEL_BLIND_BB_INPUT = "TEMPLATE_PROBEDEALER_PANEL_BLIND_BB_INPUT";
	ns.Defines.TEMPLATE_PROBEDEALER_PANEL_HANDCOUNT = "TEMPLATE_PROBEDEALER_PANEL_HANDCOUNT";
	ns.Defines.TEMPLATE_PROBEDEALER_PANEL_HANDCOUNT_LABEL = "TEMPLATE_PROBEDEALER_PANEL_HANDCOUNT_LABEL";
	ns.Defines.TEMPLATE_PROBEDEALER_PANEL_HANDCOUNT_INPUT = "TEMPLATE_PROBEDEALER_PANEL_HANDCOUNT_INPUT";
	ns.Defines.TEMPLATE_PROBEDEALER_PANEL_LASTUPDATE = "TEMPLATE_PROBEDEALER_PANEL_LASTUPDATE";
	ns.Defines.TEMPLATE_PROBEDEALER_PANEL_BETTINGROUND = "TEMPLATE_PROBEDEALER_PANEL_BETTINGROUND";
	ns.Defines.TEMPLATE_PROBEDEALER_PANEL_BETTINGROUND_DEAL = "TEMPLATE_PROBEDEALER_PANEL_BETTINGROUND_DEAL";
	ns.Defines.TEMPLATE_PROBEDEALER_PANEL_BETTINGROUND_PREFLOP = "TEMPLATE_PROBEDEALER_PANEL_BETTINGROUND_PREFLOP";
	ns.Defines.TEMPLATE_PROBEDEALER_PANEL_BETTINGROUND_FLOP = "TEMPLATE_PROBEDEALER_PANEL_BETTINGROUND_FLOP";
	ns.Defines.TEMPLATE_PROBEDEALER_PANEL_BETTINGROUND_TURN = "TEMPLATE_PROBEDEALER_PANEL_BETTINGROUND_TURN";
	ns.Defines.TEMPLATE_PROBEDEALER_PANEL_BETTINGROUND_RIVER = "TEMPLATE_PROBEDEALER_PANEL_BETTINGROUND_RIVER";
	ns.Defines.TEMPLATE_PROBEDEALER_PANEL_BETTINGROUND_END = "TEMPLATE_PROBEDEALER_PANEL_BETTINGROUND_END";
	ns.Defines.TEMPLATE_PROBEDEALER_PANEL_CONTROL_NEXT_HAND = "TEMPLATE_PROBEDEALER_PANEL_CONTROL_NEXT_HAND";

	// HTML テンプレート: モニターパネル(プレイヤー)
	ns.Defines.TEMPLATE_MONITORPLAYER_PANEL = "TEMPLATE_MONITORPLAYER_PANEL";
	ns.Defines.TEMPLATE_MONITORPLAYER_PANEL_DRAGABLE_ROOT = "TEMPLATE_MONITORPLAYER_PANEL_DRAGABLE_ROOT";
	ns.Defines.TEMPLATE_MONITORPLAYER_PANEL_LAYOUT_ROOT = "TEMPLATE_MONITORPLAYER_PANEL_LAYOUT_ROOT";
	ns.Defines.TEMPLATE_MONITORPLAYER_PANEL_NAME_VALUE = "TEMPLATE_MONITORPLAYER_PANEL_NAME_VALUE";
	ns.Defines.TEMPLATE_MONITORPLAYER_PANEL_WINRATE_VALUE = "TEMPLATE_MONITORPLAYER_PANEL_WINRATE_VALUE";
	ns.Defines.TEMPLATE_MONITORPLAYER_PANEL_ACTION_VALUE = "TEMPLATE_MONITORPLAYER_PANEL_ACTION_VALUE";
	ns.Defines.TEMPLATE_MONITORPLAYER_PANEL_POSITION_VALUE = "TEMPLATE_MONITORPLAYER_PANEL_POSITION_VALUE";
	ns.Defines.TEMPLATE_MONITORPLAYER_PANEL_HOLECARD = "TEMPLATE_MONITORPLAYER_PANEL_HOLECARD";
	ns.Defines.TEMPLATE_MONITORPLAYER_PANEL_HOLECARD_VALUE = "TEMPLATE_MONITORPLAYER_PANEL_HOLECARD_VALUE";

	// HTML テンプレート: モニターパネル(ディーラー)
	ns.Defines.TEMPLATE_MONITORDEALER_PANEL = "TEMPLATE_MONITORDEALER_PANEL";
	ns.Defines.TEMPLATE_MONITORDEALER_PANEL_DRAGABLE_ROOT = "TEMPLATE_MONITORDEALER_PANEL_DRAGABLE_ROOT";
	ns.Defines.TEMPLATE_MONITORDEALER_PANEL_LAYOUT_ROOT = "TEMPLATE_MONITORDEALER_PANEL_LAYOUT_ROOT";
	ns.Defines.TEMPLATE_MONITORDEALER_PANEL_BOARD = "TEMPLATE_MONITORDEALER_PANEL_BOARD";
	ns.Defines.TEMPLATE_MONITORDEALER_PANEL_HANDCOUNT = "TEMPLATE_MONITORDEALER_PANEL_HANDCOUNT";
	ns.Defines.TEMPLATE_MONITORDEALER_PANEL_BLIND = "TEMPLATE_MONITORDEALER_PANEL_BLIND";

	// =====================================================================
	// ポジション関連
	// =====================================================================
	// ポジション名
	ns.Defines.POKER_POSITION_DEALER = "D";
	ns.Defines.POKER_POSITION_CUTOFF = "CO";
	ns.Defines.POKER_POSITION_LOJACK = "LJ";
	ns.Defines.POKER_POSITION_HIJACK = "HJ";
	ns.Defines.POKER_POSITION_MIDDLEp1 = "MP1";
	ns.Defines.POKER_POSITION_MIDDLE = "MP";
	ns.Defines.POKER_POSITION_UTGp2 = "UTG2";
	ns.Defines.POKER_POSITION_UTGp1 = "UTG1";
	ns.Defines.POKER_POSITION_UTG = "UTG";
	ns.Defines.POKER_POSITION_BB = "BB";
	ns.Defines.POKER_POSITION_SB = "SB";
	ns.Defines.POKER_POSITION_OPENSEAT = "-";

	// ポジションリスト。ポジションの悪い方から
	const POKER_POSITION_TABLE = [
		// あると便利なので定義してるだけ
		[ns.Defines.POKER_POSITION_OPENSEAT],
		[ns.Defines.POKER_POSITION_DEALER],
		// ヘッズアップ
		[ns.Defines.POKER_POSITION_DEALER, ns.Defines.POKER_POSITION_BB],
		// 3 名
		[ns.Defines.POKER_POSITION_DEALER, ns.Defines.POKER_POSITION_BB, ns.Defines.POKER_POSITION_SB],
		// 4 名
		[ns.Defines.POKER_POSITION_DEALER, ns.Defines.POKER_POSITION_CUTOFF, ns.Defines.POKER_POSITION_BB, ns.Defines.POKER_POSITION_SB],
		// 5 名
		[ns.Defines.POKER_POSITION_DEALER, ns.Defines.POKER_POSITION_CUTOFF, ns.Defines.POKER_POSITION_HIJACK, ns.Defines.POKER_POSITION_BB, ns.Defines.POKER_POSITION_SB],
		// 6 名
		[ns.Defines.POKER_POSITION_DEALER, ns.Defines.POKER_POSITION_CUTOFF, ns.Defines.POKER_POSITION_HIJACK, ns.Defines.POKER_POSITION_LOJACK, ns.Defines.POKER_POSITION_BB, ns.Defines.POKER_POSITION_SB],
		// 7 名
		[ns.Defines.POKER_POSITION_DEALER, ns.Defines.POKER_POSITION_CUTOFF, ns.Defines.POKER_POSITION_HIJACK, ns.Defines.POKER_POSITION_LOJACK, ns.Defines.POKER_POSITION_UTG, ns.Defines.POKER_POSITION_BB, ns.Defines.POKER_POSITION_SB],
		// 8 名
		[ns.Defines.POKER_POSITION_DEALER, ns.Defines.POKER_POSITION_CUTOFF, ns.Defines.POKER_POSITION_HIJACK, ns.Defines.POKER_POSITION_LOJACK, ns.Defines.POKER_POSITION_UTGp1, ns.Defines.POKER_POSITION_UTG, ns.Defines.POKER_POSITION_BB, ns.Defines.POKER_POSITION_SB],
		// 9 名
		[ns.Defines.POKER_POSITION_DEALER, ns.Defines.POKER_POSITION_CUTOFF, ns.Defines.POKER_POSITION_HIJACK, ns.Defines.POKER_POSITION_LOJACK, ns.Defines.POKER_POSITION_UTGp2, ns.Defines.POKER_POSITION_UTGp1, ns.Defines.POKER_POSITION_UTG, ns.Defines.POKER_POSITION_BB, ns.Defines.POKER_POSITION_SB],
		// 10 名
		[ns.Defines.POKER_POSITION_DEALER, ns.Defines.POKER_POSITION_CUTOFF, ns.Defines.POKER_POSITION_HIJACK, ns.Defines.POKER_POSITION_LOJACK, ns.Defines.POKER_POSITION_MIDDLE, ns.Defines.POKER_POSITION_UTGp2, ns.Defines.POKER_POSITION_UTGp1, ns.Defines.POKER_POSITION_UTG, ns.Defines.POKER_POSITION_BB, ns.Defines.POKER_POSITION_SB],
	];

	// 人数とディーラーに対しての残り人数からポジションを求める。
	ns.Defines.convertPositionName = function(argPlayerCount, argPositionIndex)
	{
		return POKER_POSITION_TABLE[argPlayerCount][argPositionIndex];
	}
	
})(Monitor = Monitor || {});
