(function (ns) {
	if(	ns.Defines )
	{
		return;
	}

    ns.Defines = {}
    ns.Defines.VERSION = "00.03.00";

    // ブルートゥース関連
	ns.Defines.BLE_DEVICE_NAME_PREFIX = "PTV_PP_";
	ns.Defines.BLE_UUID_SERVICE = "cbaabb28-4e81-49c4-b775-aedfd27d8db0";
	ns.Defines.BLE_UUID_CHARACTERISTIC_TX = "45f116ee-b087-4271-888d-a15eebebd2eb"; // デバイス→ブラウザ
	ns.Defines.BLE_UUID_CHARACTERISTIC_RX = "45f116ee-b087-4271-888d-a15eebebd2ee"; // ブラウザ→デバイス

    // HTML コマンド実行関連
    ns.Defines.COMMAND_PROVE_DEVICE_MANAGER_SCAN = "COMMAND_PROVE_DEVICE_MANAGER_SCAN";
    ns.Defines.COMMAND_DEVELOP_PROVE_DEVICE_MANAGER_DUMP_STATUS = "COMMAND_DEVELOP_PROVE_DEVICE_MANAGER_DUMP_STATUS";
	ns.Defines.COMMAND_DEVELOP_PROVE_DEVICE_MANAGER_TEST_SCAN_OFF = "COMMAND_DEVELOP_PROVE_DEVICE_MANAGER_TEST_SCAN_OFF";
	ns.Defines.COMMAND_DEVELOP_PROVE_DEVICE_MANAGER_TEST_SCAN_ON = "COMMAND_DEVELOP_PROVE_DEVICE_MANAGER_TEST_SCAN_ON";

	// HTML コンテナ
	ns.Defines.CONTAINER_PROBEPLAYER_PANEL = "CONTAINER_PROBEPLAYER_PANEL";
	ns.Defines.CONTAINER_PROBEDEALER_PANEL = "CONTAINER_PROBEDEALER_PANEL";

	// HTML テンプレート: プローブパネル(共通)
    ns.Defines.TEMPLATE_PROBE_PANEL_STATUS_LABEL = "TEMPLATE_PROBE_PANEL_STATUS_LABEL";
    ns.Defines.TEMPLATE_PROBE_PANEL_STATUS_VALUE = "TEMPLATE_PROBE_PANEL_STATUS_VALUE";
    ns.Defines.TEMPLATE_PROBE_PANEL_BATTERY_LABEL = "TEMPLATE_PROBE_PANEL_BATTERY_LABEL";
    ns.Defines.TEMPLATE_PROBE_PANEL_BATTERY_VALUE = "TEMPLATE_PROBE_PANEL_BATTERY_VALUE";
    ns.Defines.TEMPLATE_PROBE_PANEL_LASTUPDATE_LABEL = "TEMPLATE_PROBE_PANEL_LASTUPDATE_LABEL";
    ns.Defines.TEMPLATE_PROBE_PANEL_LASTUPDATE_VALUE = "TEMPLATE_PROBE_PANEL_LASTUPDATE_VALUE";

	// HTML テンプレート: プローブパネル(プレイヤー)
	ns.Defines.TEMPLATE_PROBEPLAYER_PANEL = "TEMPLATE_PROBEPLAYER_PANEL";
    ns.Defines.TEMPLATE_PROBEPLAYER_PANEL_STATUS = "TEMPLATE_PROBEPLAYER_PANEL_STATUS";
    ns.Defines.TEMPLATE_PROBEPLAYER_PANEL_BATTERY = "TEMPLATE_PROBEPLAYER_PANEL_BATTERY";
    ns.Defines.TEMPLATE_PROBEPLAYER_PANEL_NAME = "TEMPLATE_PROBEPLAYER_PANEL_NAME";
    ns.Defines.TEMPLATE_PROBEPLAYER_PANEL_NAME_LABEL = "TEMPLATE_PROBEPLAYER_PANEL_NAME_LABEL";
    ns.Defines.TEMPLATE_PROBEPLAYER_PANEL_NAME_VALUE = "TEMPLATE_PROBEPLAYER_PANEL_NAME_VALUE";
    ns.Defines.TEMPLATE_PROBEPLAYER_PANEL_NICK = "TEMPLATE_PROBEPLAYER_PANEL_NICK";
    ns.Defines.TEMPLATE_PROBEPLAYER_PANEL_NICK_LABEL = "TEMPLATE_PROBEPLAYER_PANEL_NICK_LABEL";
    ns.Defines.TEMPLATE_PROBEPLAYER_PANEL_NICK_VALUE = "TEMPLATE_PROBEPLAYER_PANEL_NICK_VALUE";
    ns.Defines.TEMPLATE_PROBEDEALER_PANEL_LASTUPDATE = "TEMPLATE_PROBEDEALER_PANEL_LASTUPDATE";

	// HTML テンプレート: プローブパネル(ディーラー)
	ns.Defines.TEMPLATE_PROBEDEALER_PANEL = "TEMPLATE_PROBEDEALER_PANEL";
    ns.Defines.TEMPLATE_PROBEDEALER_PANEL_STATUS = "TEMPLATE_PROBEDEALER_PANEL_STATUS";
    ns.Defines.TEMPLATE_PROBEDEALER_PANEL_BATTERY = "TEMPLATE_PROBEDEALER_PANEL_BATTERY";
	ns.Defines.TEMPLATE_PROBEDEALER_PANEL_BOARD = "TEMPLATE_PROBEDEALER_PANEL_BOARD";
	ns.Defines.TEMPLATE_PROBEDEALER_PANEL_FLOP_VALUE = "TEMPLATE_PROBEDEALER_PANEL_FLOP_VALUE";
	ns.Defines.TEMPLATE_PROBEDEALER_PANEL_TURN_VALUE = "TEMPLATE_PROBEDEALER_PANEL_TURN_VALUE";
	ns.Defines.TEMPLATE_PROBEDEALER_PANEL_RIVER_VALUE = "TEMPLATE_PROBEDEALER_PANEL_RIVER_VALUE";
	ns.Defines.TEMPLATE_PROBEDEALER_PANEL_BLIND = "TEMPLATE_PROBEDEALER_PANEL_BLIND";
	ns.Defines.TEMPLATE_PROBEDEALER_PANEL_BLIND_SB_INPUT = "TEMPLATE_PROBEDEALER_PANEL_BLIND_SB_VALUE";
	ns.Defines.TEMPLATE_PROBEDEALER_PANEL_BLIND_BB_INPUT = "TEMPLATE_PROBEDEALER_PANEL_BLIND_BB_VALUE";
	ns.Defines.TEMPLATE_PROBEDEALER_PANEL_HANDCOUNT = "TEMPLATE_PROBEDEALER_PANEL_HANDCOUNT";
	ns.Defines.TEMPLATE_PROBEDEALER_PANEL_HANDCOUNT_LABEL = "TEMPLATE_PROBEDEALER_PANEL_HANDCOUNT_LABEL";
	ns.Defines.TEMPLATE_PROBEDEALER_PANEL_HANDCOUNT_VALUE = "TEMPLATE_PROBEDEALER_PANEL_HANDCOUNT_VALUE";
	ns.Defines.TEMPLATE_PROBEDEALER_PANEL_LASTUPDATE = "TEMPLATE_PROBEDEALER_PANEL_LASTUPDATE";

})(Monitor = Monitor || {});
